# Generated by Django 4.1 on 2022-08-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyBC', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='providers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': True},
        ),
    ]
